# CMake generated Testfile for 
# Source directory: /Users/mairinoshaughnessy/oath-zk-online-fairness/test
# Build directory: /Users/mairinoshaughnessy/oath-zk-online-fairness/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[basic_zk]=] "./run" "/Users/mairinoshaughnessy/oath-zk-online-fairness/bin/test_basic_zk")
set_tests_properties([=[basic_zk]=] PROPERTIES  WORKING_DIRECTORY "/Users/mairinoshaughnessy/oath-zk-online-fairness/" _BACKTRACE_TRIPLES "/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;14;add_test;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;21;add_test_case_with_run;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;0;")
add_test([=[service_phase_bench]=] "./run" "/Users/mairinoshaughnessy/oath-zk-online-fairness/bin/test_service_phase_bench")
set_tests_properties([=[service_phase_bench]=] PROPERTIES  WORKING_DIRECTORY "/Users/mairinoshaughnessy/oath-zk-online-fairness/" _BACKTRACE_TRIPLES "/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;14;add_test;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;22;add_test_case_with_run;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;0;")
add_test([=[audit_phase_fair_check_bench]=] "./run" "/Users/mairinoshaughnessy/oath-zk-online-fairness/bin/test_audit_phase_fair_check_bench")
set_tests_properties([=[audit_phase_fair_check_bench]=] PROPERTIES  WORKING_DIRECTORY "/Users/mairinoshaughnessy/oath-zk-online-fairness/" _BACKTRACE_TRIPLES "/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;14;add_test;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;23;add_test_case_with_run;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;0;")
add_test([=[audit_phase_sensitive_attr_bench]=] "./run" "/Users/mairinoshaughnessy/oath-zk-online-fairness/bin/test_audit_phase_sensitive_attr_bench")
set_tests_properties([=[audit_phase_sensitive_attr_bench]=] PROPERTIES  WORKING_DIRECTORY "/Users/mairinoshaughnessy/oath-zk-online-fairness/" _BACKTRACE_TRIPLES "/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;14;add_test;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;24;add_test_case_with_run;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;0;")
add_test([=[audit_phase_balanced_sample_bench]=] "./run" "/Users/mairinoshaughnessy/oath-zk-online-fairness/bin/test_audit_phase_balanced_sample_bench")
set_tests_properties([=[audit_phase_balanced_sample_bench]=] PROPERTIES  WORKING_DIRECTORY "/Users/mairinoshaughnessy/oath-zk-online-fairness/" _BACKTRACE_TRIPLES "/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;14;add_test;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;25;add_test_case_with_run;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;0;")
add_test([=[audit_phase_correctness_check_bench]=] "./run" "/Users/mairinoshaughnessy/oath-zk-online-fairness/bin/test_audit_phase_correctness_check_bench")
set_tests_properties([=[audit_phase_correctness_check_bench]=] PROPERTIES  WORKING_DIRECTORY "/Users/mairinoshaughnessy/oath-zk-online-fairness/" _BACKTRACE_TRIPLES "/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;14;add_test;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;26;add_test_case_with_run;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;0;")
add_test([=[audit_phase_fair_check_bench_IF]=] "./run" "/Users/mairinoshaughnessy/oath-zk-online-fairness/bin/test_audit_phase_fair_check_bench_IF")
set_tests_properties([=[audit_phase_fair_check_bench_IF]=] PROPERTIES  WORKING_DIRECTORY "/Users/mairinoshaughnessy/oath-zk-online-fairness/" _BACKTRACE_TRIPLES "/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;14;add_test;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;27;add_test_case_with_run;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;0;")
add_test([=[sha256]=] "./run" "/Users/mairinoshaughnessy/oath-zk-online-fairness/bin/test_sha256")
set_tests_properties([=[sha256]=] PROPERTIES  WORKING_DIRECTORY "/Users/mairinoshaughnessy/oath-zk-online-fairness/" _BACKTRACE_TRIPLES "/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;14;add_test;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;28;add_test_case_with_run;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;0;")
add_test([=[lowmc]=] "./run" "/Users/mairinoshaughnessy/oath-zk-online-fairness/bin/test_lowmc")
set_tests_properties([=[lowmc]=] PROPERTIES  WORKING_DIRECTORY "/Users/mairinoshaughnessy/oath-zk-online-fairness/" _BACKTRACE_TRIPLES "/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;14;add_test;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;29;add_test_case_with_run;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;0;")
add_test([=[balanced_sample_unit]=] "./run" "/Users/mairinoshaughnessy/oath-zk-online-fairness/bin/test_balanced_sample_unit")
set_tests_properties([=[balanced_sample_unit]=] PROPERTIES  WORKING_DIRECTORY "/Users/mairinoshaughnessy/oath-zk-online-fairness/" _BACKTRACE_TRIPLES "/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;14;add_test;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;30;add_test_case_with_run;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;0;")
add_test([=[unit_utils]=] "./run" "/Users/mairinoshaughnessy/oath-zk-online-fairness/bin/test_unit_utils")
set_tests_properties([=[unit_utils]=] PROPERTIES  WORKING_DIRECTORY "/Users/mairinoshaughnessy/oath-zk-online-fairness/" _BACKTRACE_TRIPLES "/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;14;add_test;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;31;add_test_case_with_run;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;0;")
add_test([=[ro_ram_test]=] "./run" "/Users/mairinoshaughnessy/oath-zk-online-fairness/bin/test_ro_ram_test")
set_tests_properties([=[ro_ram_test]=] PROPERTIES  WORKING_DIRECTORY "/Users/mairinoshaughnessy/oath-zk-online-fairness/" _BACKTRACE_TRIPLES "/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;14;add_test;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;32;add_test_case_with_run;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;0;")
add_test([=[nn_unit]=] "./run" "/Users/mairinoshaughnessy/oath-zk-online-fairness/bin/test_nn_unit")
set_tests_properties([=[nn_unit]=] PROPERTIES  WORKING_DIRECTORY "/Users/mairinoshaughnessy/oath-zk-online-fairness/" _BACKTRACE_TRIPLES "/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;14;add_test;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;33;add_test_case_with_run;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;0;")
add_test([=[nn_baseline_bench]=] "./run" "/Users/mairinoshaughnessy/oath-zk-online-fairness/bin/test_nn_baseline_bench")
set_tests_properties([=[nn_baseline_bench]=] PROPERTIES  WORKING_DIRECTORY "/Users/mairinoshaughnessy/oath-zk-online-fairness/" _BACKTRACE_TRIPLES "/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;14;add_test;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;34;add_test_case_with_run;/Users/mairinoshaughnessy/oath-zk-online-fairness/test/CMakeLists.txt;0;")
