# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mairinoshaughnessy/oath-zk-online-fairness

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mairinoshaughnessy/oath-zk-online-fairness

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mairinoshaughnessy/oath-zk-online-fairness/CMakeFiles /Users/mairinoshaughnessy/oath-zk-online-fairness//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mairinoshaughnessy/oath-zk-online-fairness/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mairinoshaughnessy/oath-zk-online-fairness/CMakeFiles /Users/mairinoshaughnessy/oath-zk-online-fairness//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mairinoshaughnessy/oath-zk-online-fairness/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_basic_zk

# Build rule for target.
test_basic_zk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_basic_zk
.PHONY : test_basic_zk

# fast build rule for target.
test_basic_zk/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_basic_zk.dir/build.make test/CMakeFiles/test_basic_zk.dir/build
.PHONY : test_basic_zk/fast

#=============================================================================
# Target rules for targets named test_service_phase_bench

# Build rule for target.
test_service_phase_bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_service_phase_bench
.PHONY : test_service_phase_bench

# fast build rule for target.
test_service_phase_bench/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_service_phase_bench.dir/build.make test/CMakeFiles/test_service_phase_bench.dir/build
.PHONY : test_service_phase_bench/fast

#=============================================================================
# Target rules for targets named test_audit_phase_fair_check_bench

# Build rule for target.
test_audit_phase_fair_check_bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_audit_phase_fair_check_bench
.PHONY : test_audit_phase_fair_check_bench

# fast build rule for target.
test_audit_phase_fair_check_bench/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_audit_phase_fair_check_bench.dir/build.make test/CMakeFiles/test_audit_phase_fair_check_bench.dir/build
.PHONY : test_audit_phase_fair_check_bench/fast

#=============================================================================
# Target rules for targets named test_audit_phase_sensitive_attr_bench

# Build rule for target.
test_audit_phase_sensitive_attr_bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_audit_phase_sensitive_attr_bench
.PHONY : test_audit_phase_sensitive_attr_bench

# fast build rule for target.
test_audit_phase_sensitive_attr_bench/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_audit_phase_sensitive_attr_bench.dir/build.make test/CMakeFiles/test_audit_phase_sensitive_attr_bench.dir/build
.PHONY : test_audit_phase_sensitive_attr_bench/fast

#=============================================================================
# Target rules for targets named test_audit_phase_balanced_sample_bench

# Build rule for target.
test_audit_phase_balanced_sample_bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_audit_phase_balanced_sample_bench
.PHONY : test_audit_phase_balanced_sample_bench

# fast build rule for target.
test_audit_phase_balanced_sample_bench/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_audit_phase_balanced_sample_bench.dir/build.make test/CMakeFiles/test_audit_phase_balanced_sample_bench.dir/build
.PHONY : test_audit_phase_balanced_sample_bench/fast

#=============================================================================
# Target rules for targets named test_audit_phase_correctness_check_bench

# Build rule for target.
test_audit_phase_correctness_check_bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_audit_phase_correctness_check_bench
.PHONY : test_audit_phase_correctness_check_bench

# fast build rule for target.
test_audit_phase_correctness_check_bench/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_audit_phase_correctness_check_bench.dir/build.make test/CMakeFiles/test_audit_phase_correctness_check_bench.dir/build
.PHONY : test_audit_phase_correctness_check_bench/fast

#=============================================================================
# Target rules for targets named test_audit_phase_fair_check_bench_IF

# Build rule for target.
test_audit_phase_fair_check_bench_IF: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_audit_phase_fair_check_bench_IF
.PHONY : test_audit_phase_fair_check_bench_IF

# fast build rule for target.
test_audit_phase_fair_check_bench_IF/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_audit_phase_fair_check_bench_IF.dir/build.make test/CMakeFiles/test_audit_phase_fair_check_bench_IF.dir/build
.PHONY : test_audit_phase_fair_check_bench_IF/fast

#=============================================================================
# Target rules for targets named test_sha256

# Build rule for target.
test_sha256: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_sha256
.PHONY : test_sha256

# fast build rule for target.
test_sha256/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_sha256.dir/build.make test/CMakeFiles/test_sha256.dir/build
.PHONY : test_sha256/fast

#=============================================================================
# Target rules for targets named test_lowmc

# Build rule for target.
test_lowmc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_lowmc
.PHONY : test_lowmc

# fast build rule for target.
test_lowmc/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_lowmc.dir/build.make test/CMakeFiles/test_lowmc.dir/build
.PHONY : test_lowmc/fast

#=============================================================================
# Target rules for targets named test_balanced_sample_unit

# Build rule for target.
test_balanced_sample_unit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_balanced_sample_unit
.PHONY : test_balanced_sample_unit

# fast build rule for target.
test_balanced_sample_unit/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_balanced_sample_unit.dir/build.make test/CMakeFiles/test_balanced_sample_unit.dir/build
.PHONY : test_balanced_sample_unit/fast

#=============================================================================
# Target rules for targets named test_unit_utils

# Build rule for target.
test_unit_utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_unit_utils
.PHONY : test_unit_utils

# fast build rule for target.
test_unit_utils/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_unit_utils.dir/build.make test/CMakeFiles/test_unit_utils.dir/build
.PHONY : test_unit_utils/fast

#=============================================================================
# Target rules for targets named test_ro_ram_test

# Build rule for target.
test_ro_ram_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ro_ram_test
.PHONY : test_ro_ram_test

# fast build rule for target.
test_ro_ram_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_ro_ram_test.dir/build.make test/CMakeFiles/test_ro_ram_test.dir/build
.PHONY : test_ro_ram_test/fast

#=============================================================================
# Target rules for targets named test_nn_unit

# Build rule for target.
test_nn_unit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_nn_unit
.PHONY : test_nn_unit

# fast build rule for target.
test_nn_unit/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_nn_unit.dir/build.make test/CMakeFiles/test_nn_unit.dir/build
.PHONY : test_nn_unit/fast

#=============================================================================
# Target rules for targets named test_nn_baseline_bench

# Build rule for target.
test_nn_baseline_bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_nn_baseline_bench
.PHONY : test_nn_baseline_bench

# fast build rule for target.
test_nn_baseline_bench/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_nn_baseline_bench.dir/build.make test/CMakeFiles/test_nn_baseline_bench.dir/build
.PHONY : test_nn_baseline_bench/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... test_audit_phase_balanced_sample_bench"
	@echo "... test_audit_phase_correctness_check_bench"
	@echo "... test_audit_phase_fair_check_bench"
	@echo "... test_audit_phase_fair_check_bench_IF"
	@echo "... test_audit_phase_sensitive_attr_bench"
	@echo "... test_balanced_sample_unit"
	@echo "... test_basic_zk"
	@echo "... test_lowmc"
	@echo "... test_nn_baseline_bench"
	@echo "... test_nn_unit"
	@echo "... test_ro_ram_test"
	@echo "... test_service_phase_bench"
	@echo "... test_sha256"
	@echo "... test_unit_utils"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

